name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    name: Build and run benchmark
    strategy:
      matrix:
        os: [ 
          {name: ubuntu-latest, build_platform: linux},
          {name: macos-latest, build_platform: macos}
        ]
    runs-on: ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    # Some GitHub runners may not have Rust v1.66.0, which is needed for the latest workspace
    # changes to Wasmtime's Cargo.toml.
    - name: Update Rust
      run: rustup update
    # Because of the special "install LLVM" task, we need to specify which tools to use.
    - name: Build components
      run: make PLATFORM=${{ matrix.os.build_platform }}
    - name: Run benchmark - Wasmtime
      run: make benchmark
    - name: Run benchmark - WAMR
      run: make benchmark.wamr PLATFORM=${{ matrix.os.build_platform }}